package hk.edu.polyu.comp.comp2021.clevis.model;

public enum Action {
    RECTANGLE,LINE,CIRCLE,SQUARE,GROUP,UNGROUP,BOUNDINGBOX,DELETE,MOVE,PICK_AND_MOVE,INTERSECT,LIST,LISTALL,QUIT,REDO,UNDO,WARNING;
}
